services:
  postgres:
    container_name: 'postgres'
    image: postgres:17.0
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - TZ=America/Sao_Paulo
    ports:
      - "5430:5432"
    volumes:
      - pgData:/var/lib/postgresql/data
volumes:
  pgData:
    name: "pgData"